# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, unique=True)),
                ('theatreReleaseDate', models.DateField(blank=True, null=True)),
                ('theatreRelease', models.TextField(blank=True, max_length=180, null=True)),
                ('image', models.TextField(blank=True, max_length=500, null=True)),
                ('genre', models.TextField(blank=True, max_length=100, null=True)),
                ('star', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
