# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='theatreRelease',
            field=models.TextField(blank=True, max_length=380, null=True),
        ),
    ]
